### ISSUE TITLE
Cannot build against Numpy 1.10

### ISSUE THREAD

**Issue by ilanschnell** [ContinuumIO/blz#19]
When trying to build blz against Numpy 1.10, I get (on all platforms):
```
ERROR:: You need numpy 1.7 or greater to run blz!
```
I'm guessing there is a test for the Numpy version based on the first 3 characters of the version string only.

**Comment by mrocklin** [comment]
This project is deprecated and should no longer be supported in other systems.  I recommend redirecting all activities against the bcolz project.

**Comment by ilanschnell** [comment]
Ok, good to know.  I'll remove it from Anaconda then.

**Comment by mrocklin** [comment]
Excellent
